# SACADO DE LA DOCU DE GITHUB. https://docs.github.com/es/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#prerequisites
# Este flujo de trabajo usa acciones que no GitHub no certifica.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# en línea.

# GitHub recomienda anclar acciones a un SHA de confirmación.
# Para obtener una versión más reciente, debes actualizar el SHA.
# También puedes hacer referencia a una etiqueta o rama, pero la acción puede cambiar sin ninguna advertencia.

# este deploy lo he creado para hacer un deploy en gitactions, para que pueda construir y publicar una imagen Docker en la rama correspondiente, y aparte que inice sesion en mi docker hub y construya la img del docker frontend (que he escogido en este caso) y la suba a mi docker hub

name: Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }} # aqui he puesto token en cada uno donde se vea docker_token, ya que password me daba error en el deploy de git. 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Cristian esta es la version que tengo instalada

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  push_to_registry:
    name: Push Frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # aqui he puesto token en cada uno donde se vea docker_token, ya que password me daba error en el deploy de git. 

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: raulmoya/trabajo-final-dockerfrontend:2.0.0

      - name: Build and push Frontend Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./imageFrontend/Dockerfile
          push: true
          tags: raulmoya/trabajo-final-dockerfrontend:2.0.0
          labels: ${{ steps.meta.outputs.labels }}